# Generated by Django 5.2.1 on 2025-05-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
    ]
