# Generated by Django 5.2.1 on 2025-05-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoApp', '0002_remove_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='static/photos/default.jpg', upload_to='static/photos/'),
        ),
    ]
